### ISSUE TITLE
Adjust spacing between facets

### ISSUE THREAD

**Issue by jonathananolan** [grattan/grattantheme#128]
There is no right number, but perhaps a lightly larger gap would be good as default for reports.

**Comment by MattCowgill** [comment]
Thanks @jonathananolan 

We can't have different defaults for different chart types without changing the way the package works. Panel spacing is set by `theme_grattan()` (which doesn't know your intended output size) rather than `grattan_save()` (which does).

I'll increase the default spacing a little
